"""Payment method and status constants for CampusBite."""

PAYMENT_METHOD_COD = "cod"
PAYMENT_METHOD_ONLINE = "online"

PAYMENT_METHODS = {
    PAYMENT_METHOD_COD,
    PAYMENT_METHOD_ONLINE,
}

PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PROCESSING = "processing"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_CANCELLED = "cancelled"
PAYMENT_STATUS_REFUNDED = "refunded"
PAYMENT_STATUS_PARTIALLY_REFUNDED = "partially_refunded"

PAYMENT_STATUSES = {
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PROCESSING,
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_CANCELLED,
    PAYMENT_STATUS_REFUNDED,
    PAYMENT_STATUS_PARTIALLY_REFUNDED,
}

# Allowed payment_status transitions (order status is independent).
PAYMENT_STATUS_TRANSITIONS: dict[str, set[str]] = {
    PAYMENT_STATUS_PENDING: {
        PAYMENT_STATUS_PROCESSING,
        PAYMENT_STATUS_CANCELLED,
        PAYMENT_STATUS_FAILED,
    },
    PAYMENT_STATUS_PROCESSING: {
        PAYMENT_STATUS_PAID,
        PAYMENT_STATUS_FAILED,
        PAYMENT_STATUS_CANCELLED,
    },
    PAYMENT_STATUS_PAID: {
        PAYMENT_STATUS_REFUNDED,
        PAYMENT_STATUS_PARTIALLY_REFUNDED,
    },
    PAYMENT_STATUS_FAILED: {
        PAYMENT_STATUS_PROCESSING,
        PAYMENT_STATUS_CANCELLED,
    },
    PAYMENT_STATUS_CANCELLED: {
        PAYMENT_STATUS_PROCESSING,
    },
    PAYMENT_STATUS_REFUNDED: set(),
    PAYMENT_STATUS_PARTIALLY_REFUNDED: {
        PAYMENT_STATUS_REFUNDED,
        PAYMENT_STATUS_PARTIALLY_REFUNDED,
    },
}

PROVIDER_RAZORPAY = "razorpay"

# Matches current frontend checkout delivery fee.
DEFAULT_DELIVERY_FEE = 40.0
